document.addEventListener("DOMContentLoaded", function() {
  const menuBtn = document.querySelector(".menu");
  const nav = document.querySelector(".newone");

  menuBtn.addEventListener("click", function() {
    nav.classList.toggle("show");
  });
});

/* Makes the menu open and close*/
/* generated by ai*/